# Generated by Django 4.2.4 on 2024-04-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("to_do", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskmodel",
            name="description",
        ),
        migrations.AddField(
            model_name="taskmodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
